/* Rainbow Deep Field — the founding messages.
   These are here so the sky is never empty. Everything after this was left by
   somebody who came here and typed it. */
(function (RDF) {
  'use strict';

  RDF.SEEDS = [
    // — reassurance, without the greeting-card voice —
    "you're doing better than the version of you from a year ago could have hoped",
    "nobody remembers the thing you said in 2019. they were busy remembering theirs.",
    "the fact that you're worried about being a good person is most of being one",
    "it is allowed to be hard AND to be going fine at the same time",
    "you didn't waste those years. you were becoming someone who could handle this.",
    "the people who love you are not keeping score",
    "you're not behind. there was never a schedule. someone made that up.",
    "starting over at your age is still, statistically, very early",
    "you can be proud of something you also want to improve",
    "the reason it feels heavy is that you're the one carrying it. that's strength, not failure.",
    "whatever you didn't finish today will still be there, patient, tomorrow",
    "you have survived every single one of your worst days so far. that's a perfect record.",
    "not every season is for growing. some are for staying alive, and that counts.",
    "asking for help is a skill and you're allowed to still be learning it",
    "someone thinks of you far more fondly than you'd ever guess",
    "you are not too much. you were just in the wrong room.",
    "the anxious voice is not the smart one. it's just the loud one.",
    "if you're reading this at 3am: put it down. it will look different at 9.",
    "you don't have to earn rest",
    "being tired is not a character flaw",
    "your standards for yourself are higher than the ones you'd hold a friend to. notice that.",
    "you're allowed to change your mind about something you were once loud about",
    "the mess in your house is not a moral report card",
    "you have never once been as annoying as you think you were",
    "small and consistent beats enormous and once. you already know this. this is your reminder.",
    "give it one more week before you decide it's not working",
    "you are the only one auditing your life this closely",

    // — noticing things —
    "the light at 4pm in october is free and nobody talks about it enough",
    "the smell of a hardware store is genuinely one of the best smells and it's just wood and metal",
    "somewhere right now a stranger is laughing so hard they can't breathe",
    "there is a specific sound a good book makes when it closes",
    "the first cold morning where you can see your breath is a small yearly gift",
    "cold pillow. that's it. that's the message.",
    "the moment a cat decides to trust you is a real thing that happens to real people",
    "bread has been comforting people for eleven thousand years and it hasn't gotten worse at it",
    "somebody baked something today just so someone else would be happy",
    "at any given moment there are about a million people in the air above you, mostly bored",
    "your body replaced almost all of its cells since the last time you felt this way",
    "the ocean is loud on purpose",
    "a dog is currently having the best day of its life for no reason",
    "the sound of rain on a car roof is the same sound your great-grandparents loved",
    "someone is tuning a piano right now and getting it exactly right",
    "there is a bakery somewhere that opens at 4am so that your morning is better",
    "libraries still exist. buildings full of free knowledge. we just let that happen.",
    "if you press your ear to a pillow you can hear your own heartbeat and it's been doing that the whole time",
    "the smell after rain has a name. petrichor. someone bothered to name it.",
    "somewhere a kid just learned to whistle and will not stop",
    "the best chairs in the world are in the houses of people's grandmothers",
    "steam off a mug in cold air. free every time.",

    // — the universe, warmly —
    "the calcium in your teeth was forged inside a star that exploded before the sun existed",
    "every atom heavier than iron in your body came from a dying star or two colliding. you are secondhand.",
    "there is more water in space than in all of earth's oceans, drifting around as ice, waiting",
    "voyager 1 is still transmitting. it's been sending postcards home for almost fifty years.",
    "the golden record has a recording of a kiss on it. we sent a kiss into interstellar space.",
    "in 1995 hubble stared at an empty patch of sky for ten days. it was not empty. it was ten thousand galaxies.",
    "saturn's rings are mostly clean water ice, which means saturn is wearing a halo of snow",
    "there is a nebula where it rains liquid diamond, gently, forever",
    "jupiter has protected earth from comets for four billion years and has never asked for anything",
    "the moon is drifting away from us at about the speed your fingernails grow",
    "every rainbow you have ever seen was yours alone. the angle is different for everyone.",
    "you have never seen the same rainbow as another person. that's not sad. that's yours.",
    "starlight split apart is literally a rainbow, and the dark lines in it tell you what the star is made of",
    "we learned what the sun is made of by looking at its rainbow. that's how we know.",
    "helium was found in the sun before it was found on earth. we read it in the light.",
    "there is a cloud of alcohol in sagittarius b2 the size of a solar system, which is objectively funny",
    "space smells like seared steak and hot metal, according to actual astronauts",
    "the pale blue dot photo was taken because carl sagan begged them to turn the camera around",
    "there is a black hole singing a b-flat, 57 octaves below middle c, and it has been for billions of years",
    "the pillars of creation might already be gone. we're watching a photograph of something that ended.",
    "if you got in a car and drove upward at highway speed, you'd be in space in about an hour",
    "on venus a day is longer than a year, which means the calendar there would be a nightmare",
    "there are more possible chess games than atoms in the observable universe",
    "the andromeda galaxy is coming to meet us and it will be beautiful and nobody will get hurt",
    "the ISS crosses a sunrise every 90 minutes. sixteen sunrises a day. somebody sees them.",
    "we found a planet that is probably made of graphite and diamond and we called it 55 cancri e",
    "auroras are the sun's wind hitting our magnetic field. the sky is our shield glowing.",
    "titan has lakes and rivers and rain. it's just methane. but there's weather out there.",
    "there's a spacecraft that is now further from earth than anything humans have made, and it's fine",
    "we put a telescope a million miles away and it unfolded itself perfectly on the first try",
    "opportunity was supposed to last 90 days on mars. it lasted 15 years.",
    "the first thing life did on this planet was figure out how to use light. we're still doing that.",
    "cosmic background radiation is the oldest light there is and it's a faint warm hum in every direction",
    "the universe is under no obligation to be this beautiful and yet",

    // — permission —
    "you can leave the party early",
    "you can quit the book",
    "you can text them first",
    "you can wear the thing",
    "you can be bad at a hobby forever and it still counts as a hobby",
    "you can start at 34. or 51. or monday.",
    "you can like the popular thing. it's popular for a reason.",
    "you can stop explaining yourself mid-sentence",
    "you can take the long way home",
    "you can be the one who says the awkward sincere thing",
    "you can go to the movies alone and it's genuinely great",
    "you can leave the dishes. one night. as a treat.",
    "you can outgrow a version of yourself you were once very proud of",
    "you're allowed to want a small life",
    "you can order the same thing every time. the restaurant does not judge you.",
    "you can not have an opinion about that",

    // — the funny-wholesome register —
    "otters hold hands so they don't drift apart while sleeping and that's just true, look it up",
    "a group of flamingos is called a flamboyance and somebody had to decide that",
    "cows have best friends and get stressed when separated. cows. have. best friends.",
    "bees can recognise human faces. one of them might know you.",
    "wombat poop is cube shaped and scientists were genuinely excited to find out why",
    "sea otters have a favourite rock and they keep it in a pocket of skin. a favourite rock.",
    "rats laugh when tickled. ultrasonically. we had to build a machine to hear it.",
    "there is a species of jellyfish that ages backwards when stressed, which is a strategy",
    "penguins propose with a pebble. they pick the best one they can find.",
    "the loudest recorded sound on earth was krakatoa, and the second is probably a toddler at 6am",
    "octopuses have three hearts and two of them stop when they swim, so swimming makes them tired. relatable.",
    "sloths sometimes grab their own arm thinking it's a branch. we all have days.",
    "puffins can be left-flippered and right-flippered",
    "a shrimp's heart is in its head, which explains a lot about shrimp",
    "when horses meet a horse they like, they breathe into each other's noses. that's a handshake.",
    "elephants have a specific rumble they use only for greeting friends they haven't seen in a while",
    "crows give gifts to people who feed them. shiny things. deliberately.",
    "the average cloud weighs about as much as a hundred elephants and just floats there anyway",
    "there was a cat named félicette who went to space in 1963 and came back. she made it.",
    "laika didn't, and we still name streets after her",
    "a baby puffin is called a puffling and i think about that a lot",
    "prairie dogs have words. actual nouns. they can describe the shirt you were wearing.",
    "if you sing to a cow it will come over. this is a real technique and it works.",

    // — one line, said plainly —
    "i hope your knees stop hurting",
    "i hope you get the job",
    "i hope the scan comes back clear",
    "i hope they text back",
    "i hope you find the good parking spot",
    "i hope your plant survives",
    "i hope somebody makes you tea today without being asked",
    "i hope your bus is on time and empty",
    "i hope you sleep like you did when you were nine",
    "i hope the thing you're dreading gets cancelled",
    "i hope you hear your favourite song by accident somewhere",
    "i hope your team wins",
    "i hope you laugh at something stupid today",
    "i hope somebody says your name like they're glad to",
    "i hope you get a window seat",
    "i hope it goes better than you think",
    "whatever it is, i hope it's fine",

    // — for specific people —
    "to whoever is in a hospital waiting room reading this: i'm sorry. i hope it's good news.",
    "to whoever is about to send a scary email: send it. it's fine. it's a normal email.",
    "to the person who moved somewhere new and hasn't made friends yet: it takes about eight months. hang on.",
    "to whoever is caring for a parent right now: what you're doing is enormous and mostly invisible. i see it.",
    "to whoever just got dumped: you will one day be relieved. not yet. but one day.",
    "to whoever is up feeding a baby at 4am: you are not the only light on",
    "to the night shift: thank you. genuinely. the world runs because you're awake.",
    "to whoever is studying for something brutal: you will not remember this week. you'll remember passing.",
    "to whoever is the first in their family to do this: that's a big deal and nobody around you knows how big",
    "to whoever is far from home right now: it's still home. it stays home. you can go back.",
    "to whoever is deciding whether to go to the thing: go to the thing",
    "to whoever is stuck in traffic: everyone around you is also a whole person with a whole life. weird, right?",
    "to whoever just made a mistake at work: nobody will remember by thursday",
    "to the person who always organises everything for everyone: someone noticed. it was me. i noticed.",
    "to whoever is trying to quit something: today only. just today. that's the whole task.",
    "to whoever has been strong for a long time: you can put it down for an hour",

    // — small useful truths —
    "you can leave a voicemail saying only 'no reason, just thinking about you' and it will make someone's month",
    "the cure for feeling useless is usually to do one small useful thing badly",
    "almost everyone is too worried about themselves to be judging you. this is either sad or freeing. pick freeing.",
    "'i don't know' is a complete sentence and it makes you more credible, not less",
    "drink some water. i know. but drink some water.",
    "go outside for four minutes. that's it. four.",
    "text the friend you've been meaning to text. it has not been too long.",
    "it has not been too long. it is never too long. they'll be happy.",
    "if you're stuck, make the task smaller until it's stupid, then do the stupid version",
    "you will never regret going to bed at a reasonable hour",
    "put the thing you keep losing in one specific place. name the place. that's the whole system.",
    "call your grandmother",
    "learn one recipe by heart. it will feed you for the rest of your life.",
    "the first draft is supposed to be bad. that's what it's for.",
    "if two people you trust say the same thing about you, it's probably true. that goes for good things too.",
    "compliment the thing people chose, not the thing they were born with",
    "when someone tells you about a problem, ask if they want help or company. it's a magic question.",
    "the friendship doesn't need an occasion",

    // — a little strange —
    "somewhere in the world there is a lighthouse keeper and they're doing fine",
    "every train timetable is a promise made by strangers to strangers, and it mostly works",
    "someone maintains the font you're reading this in. that's their job. they care about the letter g.",
    "a person you have never met made the road you drove on today, and did it properly",
    "there is a man in japan who has run a tiny record shop for fifty years and it's still open",
    "somebody is currently restoring a very old painting one square centimetre at a time",
    "there are people whose entire job is to make sure the clocks agree with each other",
    "there's a seed vault in the arctic holding a million kinds of plant, in case. just in case.",
    "somebody wrote down the recipe so that you could still have it a hundred years later",
    "a stranger held a door for someone today and neither of them will remember it and it still happened",
    "the guy who invented the pop-tab on cans is buried with one. that's a real thing.",
    "there are more trees on earth than stars in the milky way, by a factor of about four",
    "someone is teaching someone else to swim right now",
    "every language on earth has a word for the feeling of missing someone",
    "human beings have been drawing hands on cave walls for forty thousand years. same hands.",
    "the oldest known melody is 3400 years old and we can still play it and it still sounds like music",
    "somebody out there is genuinely excellent at a thing you've never heard of",
    "the word 'you' in this sentence is doing a lot of work across a lot of time",

    // — closing the loop —
    "if this is the only nice thing you read today, i'm glad it got to you",
    "somebody typed this by hand and then sent it into the dark hoping you'd find it. you did.",
    "you found this. out of all of them. that's a small unlikely thing and it happened.",
    "leave one for the next person",
    "the whole point is that someone was thinking of a stranger. that was you. hello.",
    "this took twelve seconds to write and it might last longer than that in you",
    "i'll never know if you saw this and i'm sending it anyway",
    "hello from earlier",

    // — time, and being a person in it —
    "you are allowed to be a beginner at something at any age. the alternative is never starting.",
    "in ten years you will miss something about right now. probably something small.",
    "the version of you that was terrified of that thing you do easily now would be so relieved",
    "nostalgia is just proof you had something worth missing",
    "you will not always feel like this. that's the whole deal with feelings.",
    "old people almost never say they wish they'd worried more",
    "your twenties are not a deadline. neither are your thirties. there is no deadline.",
    "somebody in their eighties is learning to paint today and is bad at it and doesn't care",
    "the day you learned to read was a bigger achievement than anything you'll do this month, and you don't remember it",
    "the boring stretch in the middle is where most of the actual living happens",
    "you have already changed your entire personality at least twice and survived both",
    "if you can remember it fondly it wasn't wasted",
    "it takes about four years to build a life somewhere. that's not long. that's four years.",
    "the future you keep worrying about is going to be a tuesday",

    // — work, and the strange things people do all day —
    "somewhere a person is very carefully aligning something nobody will ever notice, and they're right to",
    "the person who wrote the manual for the thing you fixed today never met you and helped you anyway",
    "there is a whole profession dedicated to making sure bridges do not fall down and they are extremely good at it",
    "you're allowed to be proud of work nobody can see",
    "somebody has spent thirty years getting really good at one narrow thing and it's beautiful",
    "the job is not your whole personality and it never was",
    "on the worst day of your career the sun still went down normally",
    "someone laminated something today with real satisfaction",
    "the fact you care whether you're doing it well already puts you ahead",
    "you can be replaceable at your job and irreplaceable everywhere else. most people are.",
    "the meeting will end. they all do. every single one so far has ended.",
    "a stranger checked the water you drank this morning. that's a job. someone did it.",

    // — food, warmth, small physical comforts —
    "somebody somewhere is stirring something slowly and thinking about nothing",
    "soup was invented independently by nearly every culture on earth because we all worked out the same thing",
    "the first sip of something hot when your hands are cold is one of the good ones",
    "there is a person who taught you a recipe and they are in your hands whenever you make it",
    "toast. genuinely. toast.",
    "you can eat the same breakfast every day for a decade and it does not make you boring",
    "somebody is cutting fruit for someone else right now, which is one of the oldest ways to say i love you",
    "leftovers eaten standing up at the counter at midnight are a legitimate meal",
    "the last bite of something you loved is supposed to be a little sad",
    "sharing food with someone predates language. we did that before we could say why.",
    "a bad meal with good people beats the reverse every time and everyone knows it",

    // — music and the arts —
    "somebody is learning your favourite song right now and getting it slightly wrong",
    "every song you love was once a thing that did not exist",
    "the reason a minor chord feels sad is not settled science. we just all agree it does.",
    "there is a person who plays an instrument only in an empty house and is very good",
    "humming is involuntary joy leaking out",
    "somebody wrote a song about being lonely and it made millions of people feel less alone, which is a very funny outcome",
    "you don't need to be good at it to be allowed to do it",
    "the harmony you can hear but not name is the whole reason the song works",
    "someone is at a concert tonight having the best night of their year",
    "every dance is just being briefly unembarrassed and it looks incredible on everyone",

    // — more of the universe —
    "the sun loses four million tonnes of itself every second to keep us warm and has been doing it for four and a half billion years",
    "light from the sun takes eight minutes to reach you, so you have never seen the sun as it is, only as it was",
    "the atoms in your left hand probably came from a different star than the ones in your right",
    "there is a moon called enceladus that shoots seawater into space through cracks in its ice",
    "on mars, sunsets are blue. exactly backwards from ours.",
    "somewhere out there is a diamond planet and nobody can go get it, which is somehow perfect",
    "the great red spot has been a storm for longer than anyone has been watching",
    "we sent a probe past pluto and it worked, after nine years, on the first try",
    "the milky way has a smell, apparently, and it's raspberries and rum. that's the ethyl formate.",
    "space is not silent — it's just that nothing is around to carry the sound to you",
    "a day on earth is getting longer by about two milliseconds a century, so you have marginally more time than your grandparents did",
    "there are rogue planets out there with no sun at all, just drifting, and some of them might have oceans under the ice",
    "there is a star called methuselah that appears to be older than the universe and astronomers are still arguing about it, politely",
    "the light you can see from andromeda left before humans existed and arrived tonight anyway",
    "if the sun were a beach ball, earth would be a peppercorn about twenty-six metres away",
    "we have found over five thousand planets around other stars and we only started looking properly in 1995",
    "one of the moons of saturn is shaped like a walnut and nobody is quite sure why",
    "every element in the periodic table above hydrogen had to be built somewhere, by something, on purpose or by accident",
    "the cosmic microwave background is on your old television as static. a fraction of that snow is the beginning of everything.",
    "a neutron star spins hundreds of times a second and is so dense a teaspoon would weigh as much as a mountain",
    "there is a comet that comes back every seventy-five years and people plan their whole lives around seeing it twice",
    "we left footprints on the moon and there is no weather there to erase them",
    "gravitational waves were predicted a hundred years before we could hear one, and then we heard one",
    "the james webb telescope has a sunshield the size of a tennis court and it unfolded in the dark, alone, perfectly",

    // — animals, part two —
    "goats have accents. herds from different places bleat differently.",
    "a group of pugs is called a grumble, which is correct",
    "chickens can be optimistic or pessimistic and you can test for it",
    "dolphins have names for each other. actual signature whistles.",
    "a snail can sleep for three years and honestly, fair",
    "narwhal tusks are teeth. a very long, very sensitive tooth, growing straight forward.",
    "bumblebees have to learn to fly. their first attempts are terrible.",
    "the mimic octopus can impersonate at least fifteen other species and is showing off",
    "swifts can stay in the air for ten months without landing. they sleep up there.",
    "seahorses hold tails when they travel together",
    "a bat will share food with a bat that shared with it before, and remembers who didn't",
    "cats purr at a frequency that may help their own bones heal, so it's a self-repair system that also makes you happy",
    "moths aren't attracted to light — they get confused by it and can't navigate. they're lost, not drawn.",
    "a starling murmuration has no leader. every bird is just watching seven neighbours.",
    "orcas have grandmothers who lead the pod for decades after they stop having calves",
    "trees in a forest send each other sugar through fungal networks, including to stumps that can't photosynthesise any more",
    "there is a tree in sweden whose root system is nine thousand years old",
    "some whales sing songs that change slightly every year, and the whole ocean learns the new version",

    // — small strange comforts —
    "somewhere there's a library book with a note left in it by a stranger, waiting",
    "someone has been feeding the same neighbourhood cat for six years",
    "there is a bench somewhere with your name on it in the future, probably",
    "every jar of honey you've eaten was made by insects that had no idea",
    "there are people whose job is to name paint colours and they are having a wonderful time",
    "an airport at 5am is one of the strangest and gentlest places on earth",
    "somebody kept the drawing you made when you were six",
    "you have been someone's good day and you will never know which day",
    "a stranger's playlist is a small autobiography and you can just listen to it",
    "there is a man who has photographed the same tree every day for twenty years",
    "somebody built the chair you are sitting on and hoped it would hold",
    "the letters on old buildings were painted by hand by someone standing on a ladder",
    "there is a lost sock somewhere living a full life",
    "the number of people who have been kind to you without you noticing is enormous",

    // — more permission —
    "you can be the friend who suggests things",
    "you can cry at the film. that's what it's for.",
    "you can not finish the degree",
    "you can call in sick when you are tired rather than ill",
    "you can rearrange the furniture on a wednesday for no reason",
    "you can say 'i don't want to' without a follow-up clause",
    "you can be terrible at small talk and still be extremely good company",
    "you can start the day again at 3pm",
    "you can love a place you'll never live in",
    "you can keep a hobby entirely secret",
    "you can stop replying to that group chat",
    "you can go back to the same holiday spot every year forever",
    "you can be the one who remembers birthdays even if nobody remembers yours",
    "you can eat dinner at 4pm like a small european town",

    // — the plain ones —
    "i hope somebody laughs at your joke today",
    "i hope you find money in an old coat",
    "i hope your favourite place is still there",
    "i hope the thing you ordered fits",
    "i hope the meeting gets moved",
    "i hope you sleep through the night",
    "i hope it stops hurting",
    "i hope somebody surprises you",
    "i hope your friend calls",
    "i hope the sky does something good on your way home",
    "i hope you catch the light at the right moment",
    "i hope this finds you at a good time",

    // — for specific people, part two —
    "to whoever is doing this alone: it counts double and somebody should tell you that",
    "to whoever just moved back in with their parents: it's a strategy, not a verdict",
    "to whoever is between things right now: the gap is not the story, it's the page break",
    "to whoever is teaching themselves at 11pm after work: that's the hard way and it's the real way",
    "to whoever is the only one in the room like them: you're not the diversity, you're the person",
    "to whoever is waiting on a decision from someone who isn't thinking about you at all: it's not personal, and it's almost never no forever",
    "to whoever got rejected today: the person who read it spent ninety seconds on it and is now eating a sandwich",
    "to whoever is going back after a long time away: they'll be glad. they always are.",
    "to whoever is scared of the phone call: write down the first sentence and then just read it",
    "to whoever has too many tabs open, literally and otherwise: close six of them, nothing will happen",
    "to whoever is doing the driving on a long trip: thank you for that",
    "to whoever is early and waiting outside: you're doing great, you're just early",
    "to the youngest person in the room: you'll be the oldest one sooner than you think, and it goes fine",
    "to whoever is holding it together in a public place right now: nobody can tell. you look completely normal.",

    // — closing, part two —
    "leave a better one than this",
    "there are hundreds of these out here and somebody meant every one of them",
    "you're roughly the thousandth person to read this exact sentence in the dark",
    "the odds of you finding this particular one were bad and here we are",
    "keep going. that's it. that's the whole message.",
    "the sky is full of these now. that happened because people kept doing it.",
    "someone will find yours the way you found this one"
  ];
})(window.RDF = window.RDF || {});
